version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: bot_redis
    restart: unless-stopped

  bot:
    build: .
    container_name: tg_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "-u", "main.py"]

 # worker:
  #  build: .
   # container_name: celery_worker
    #restart: unless-stopped
    #env_file:
     # - .env
   # depends_on:
    #  - db
     # - redis
   # command: celery -A services.celery_app worker -l info
    # если у тебя другой путь/название celery_app — скажи, подправим

volumes:
  postgres_data:
